export const GET_TODO_REQ = 'GET_TODO_REQ'
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
export const GET_TODO_FAIL = 'GET_TODO_FAIL'

export const ADD_TODO_REQ = 'ADD_TODO_REQ'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'

export const EDIT_TODO_REQ = 'EDIT_TODO_REQ'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL'

export const DELETE_TODO_REQ = 'DELETE_TODO_REQ'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL'